### ISSUE TITLE
metadata middleware is not safe for concurrent use

### ISSUE THREAD

**Issue by z760087139** [go-kratos/kratos#2865]
#### What happened:
如果通过并发读取和写入 metadata 内容，会出现 `fatal error: concurrent map read and map write`的 panic
```
WARNING: DATA RACE
Write at 0x00c00011c390 by goroutine 9:
  runtime.mapaccess2_faststr()
      /usr/local/go/src/runtime/map_faststr.go:107 +0x48c
  github.com/go-kratos/kratos/v2/metadata.Metadata.Set()
      /go/src/github.com/go-kratos/kratos/metadata/metadata.go:37 +0xf8
  github.com/go-kratos/kratos/v2/metadata.TestConcurrent.func1()
      /go/src/github.com/go-kratos/kratos/metadata/metadata_test.go:300 +0xb8

Previous write at 0x00c00011c390 by goroutine 8:
  runtime.mapaccess2_faststr()
      /usr/local/go/src/runtime/map_faststr.go:107 +0x48c
  github.com/go-kratos/kratos/v2/metadata.Metadata.Set()
     /go/src/github.com/go-kratos/kratos/metadata/metadata.go:37 +0xf8
  github.com/go-kratos/kratos/v2/metadata.TestConcurrent.func1()
      /go/src/github.com/go-kratos/kratos/metadata/metadata_test.go:300 +0xb8

Goroutine 9 (running) created at:
  github.com/go-kratos/kratos/v2/metadata.TestConcurrent()
      /go/src/github.com/go-kratos/kratos/metadata/metadata_test.go:296 +0x1cc
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x198

Goroutine 8 (finished) created at:
  github.com/go-kratos/kratos/v2/metadata.TestConcurrent()
      /go/src/github.com/go-kratos/kratos/metadata/metadata_test.go:296 +0x1cc
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x198
==================
fatal error: concurrent map writes

goroutine 29 [running]:
runtime.throw({0x104364a45, 0x15})
	/usr/local/go/src/runtime/panic.go:1198 +0x54 fp=0xc0001776a0 sp=0xc000177670 pc=0x10425d294
runtime.mapassign_faststr(0x1043ba4e0, 0xc00011c390, {0x1043681ac, 0x1})
	/usr/local/go/src/runtime/map_faststr.go:211 +0x420 fp=0xc000177720 sp=0xc0001776a0 pc=0x104238f30
github.com/go-kratos/kratos/v2/metadata.Metadata.Set(...)
	/go/src/github.com/go-kratos/kratos/metadata/metadata.go:37
github.com/go-kratos/kratos/v2/metadata.TestConcurrent.func1(0xc000126384, 0xc00011a590, 0x9)
	/go/src/github.com/go-kratos/kratos/metadata/metadata_test.go:300 +0xfc fp=0xc0001777c0 sp=0xc000177720 pc=0x10436028c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1133 +0x4 fp=0xc0001777c0 sp=0xc0001777c0 pc=0x104291274
created by github.com/go-kratos/kratos/v2/metadata.TestConcurrent
	/go/src/github.com/go-kratos/kratos/metadata/metadata_test.go:296 +0x1d0

goroutine 1 [chan receive]:
testing.(*T).Run(0xc000103380, {0x104362ee5, 0xe}, 0x1043d0100)
	/usr/local/go/src/testing/testing.go:1307 +0x5e4
testing.runTests.func1(0xc000103380)
	/usr/local/go/src/testing/testing.go:1598 +0xb0
testing.tRunner(0xc000103380, 0xc000139c18)
	/usr/local/go/src/testing/testing.go:1259 +0x19c
testing.runTests(0xc000130030, {0x1044a8840, 0xa, 0xa}, {0x0, 0x0, 0x0})
	/usr/local/go/src/testing/testing.go:1596 +0x784
testing.(*M).Run(0xc000154000)
	/usr/local/go/src/testing/testing.go:1504 +0x92c
main.main()
	_testmain.go:61 +0x28c
```

#### What you expected to happen:
metadata 中间件支持并发读取和写入
#### How to reproduce it (as minimally and precisely as possible):
```go
# github.com/go-kratos/kratos/metadata/metadata_test.go
func TestConcurrent(t *testing.T) {
	ctx := context.Background()
	md := Metadata{}
	ctx = NewServerContext(ctx, md)
	wg := sync.WaitGroup{}
	wg.Add(200)
	for i := 0; i < 100; i++ {
		go func(i int) {
			defer wg.Done()
			tr, ok := FromServerContext(ctx)
			if ok {
				tr.Set(strconv.FormatInt(int64(i), 10), "num")
			}
		}(i)
	}
	for i := 0; i < 100; i++ {
		go func() {
			defer wg.Done()
			tr, ok := FromServerContext(ctx)
			if ok {
				tr.Get("something")
			}
		}()
	}
	wg.Wait()
}
```
#### Environment:
- Kratos version (use `kratos -v`):
kratos version v2.2.0
- Go version (use `go version`):
go version go1.17.8 darwin/arm64

**Comment by GGXXLL** [comment]
Personal understanding. The source code `type Metadata map[string][]string`. It is not inherently designed for concurrency security.

**Comment by shenqidebaozi** [comment]
> Personal understanding. The source code . It is not inherently designed for concurrency security. It is usually used during a full rpc life cycle, along with context.Context. [document](https://go-kratos.dev/en/docs/component/metadata/)`type Metadata map[string][]string`

Yes, using a map itself cannot guarantee concurrency security. A `metadata` is used for the complete lifecycle of a request, and it does not involve concurrency issues because different requests use different `context` objects
