### ISSUE TITLE
net: lookupIPAddr dns resolving panic by data race.

### ISSUE THREAD

**Issue by lyouthzzz** [go-kratos/kratos#3070]
#### What happened:
go sdk net: `lookupIPAddr` dns resolving panic. This led to a crash of the Go process.

#### What you expected to happen:
I hope the Go program won't crash.

#### How to reproduce it (as minimally and precisely as possible):

```golang
package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/transport/http"
	nethttp "net/http"
	"runtime"
	"time"
)

func main() {
	runtime.GOMAXPROCS(4)

	srv := http.NewServer(http.Address(":18888"), http.Timeout(40*time.Millisecond))
	router := srv.Route("/")

	router.GET("/ping", func(ctx http.Context) error {
		req, _ := nethttp.NewRequest("GET", "http://www.baidu.com", nil)
		req = req.WithContext(ctx)
		_, _ = nethttp.DefaultClient.Do(req)
		return nil
	})

	panic(kratos.New(kratos.Server(srv)).Run())
}

```

**This is a simple demo. Run this server and start 200 threads,  make concurrent calls to the API.**

#### Anything else we need to know?:
```
go run -race main.go
```
output: 
```
==================
==================
WARNING: DATA RACE
Write at 0x00c001434808 by goroutine 283:
  github.com/go-kratos/kratos/v2/transport/http.(*wrapper).Reset()
      /Users/y.liu/go/src/github.com/go-kratos/kratos/transport/http/context.go:157 +0xe0
  github.com/go-kratos/kratos/v2/transport/http.(*Router).Handle.func1()
      /Users/y.liu/go/src/github.com/go-kratos/kratos/transport/http/router.go:57 +0x110
  net/http.HandlerFunc.ServeHTTP()
      /Users/y.liu/go/go1.20/src/net/http/server.go:2122 +0x48
  github.com/go-kratos/kratos/v2/transport/http.(*Server).filter.func1.1()
      /Users/y.liu/go/src/github.com/go-kratos/kratos/transport/http/server.go:277 +0x5b0
  net/http.HandlerFunc.ServeHTTP()
      /Users/y.liu/go/go1.20/src/net/http/server.go:2122 +0x48
  github.com/gorilla/mux.(*Router).ServeHTTP()
      /Users/y.liu/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x298
  net/http.serverHandler.ServeHTTP()
      /Users/y.liu/go/go1.20/src/net/http/server.go:2936 +0x530
  net/http.(*conn).serve()
      /Users/y.liu/go/go1.20/src/net/http/server.go:1995 +0x898
  net/http.(*Server).Serve.func3()
      /Users/y.liu/go/go1.20/src/net/http/server.go:3089 +0x4c

Previous read at 0x00c001434808 by goroutine 5404:
  github.com/go-kratos/kratos/v2/transport/http.(*wrapper).Err()
      /Users/y.liu/go/src/github.com/go-kratos/kratos/transport/http/context.go:175 +0x34
  net.(*Resolver).lookupIPAddr()
      /Users/y.liu/go/go1.20/src/net/lookup.go:349 +0xa24
  net.(*Resolver).internetAddrList()
      /Users/y.liu/go/go1.20/src/net/ipsock.go:288 +0x684
  net.(*Resolver).resolveAddrList()
      /Users/y.liu/go/go1.20/src/net/dial.go:234 +0x4bc
  net.(*Dialer).DialContext()
      /Users/y.liu/go/go1.20/src/net/dial.go:422 +0x4c4
  net.(*Dialer).DialContext-fm()
      <autogenerated>:1 +0x64
  net/http.(*Transport).dial()
      /Users/y.liu/go/go1.20/src/net/http/transport.go:1176 +0x1b8
  net/http.(*Transport).dialConn()
      /Users/y.liu/go/go1.20/src/net/http/transport.go:1614 +0x9d0
  net/http.(*Transport).dialConnFor()
      /Users/y.liu/go/go1.20/src/net/http/transport.go:1456 +0xc4
  net/http.(*Transport).queueForDial.func1()
      /Users/y.liu/go/go1.20/src/net/http/transport.go:1425 +0x40

Goroutine 283 (running) created at:
  net/http.(*Server).Serve()
      /Users/y.liu/go/go1.20/src/net/http/server.go:3089 +0x5ec
  github.com/go-kratos/kratos/v2/transport/http.(*Server).Start()
      /Users/y.liu/go/src/github.com/go-kratos/kratos/transport/http/server.go:307 +0x1ec
  github.com/go-kratos/kratos/v2.(*App).Run.func2()
      /Users/y.liu/go/src/github.com/go-kratos/kratos/app.go:112 +0x70
  golang.org/x/sync/errgroup.(*Group).Go.func1()
      /Users/y.liu/go/pkg/mod/golang.org/x/sync@v0.0.0-20220513210516-0976fa681c29/errgroup/errgroup.go:74 +0x6c
```

**finnally crash**
```
==================
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x1004c9f48]

goroutine 6296 [running]:
net.(*Resolver).lookupIPAddr(0x100c06300, {0x12a4a00d8?, 0xc000ba2b00}, {0x1006f39c6, 0x3}, {0xc000ca2790, 0xd})
        /Users/y.liu/go/go1.20/src/net/lookup.go:351 +0xaf8
net.(*Resolver).internetAddrList(0x12a4a00d8?, {0x12a4a00d8, 0xc000ba2b00}, {0x1006f39c6, 0x3}, {0xc000ca2790, 0x10})
        /Users/y.liu/go/go1.20/src/net/ipsock.go:288 +0x688
net.(*Resolver).resolveAddrList(0xc000ba2b00?, {0x12a4a00d8, 0xc000ba2b00}, {0x1006f3d15, 0x4}, {0x1006f39c6, 0x3}, {0xc000ca2790, 0x10}, {0x0?, ...})
        /Users/y.liu/go/go1.20/src/net/dial.go:234 +0x4c0
net.(*Dialer).DialContext(0xc0000df9d0, {0x12a4a00d8, 0xc000ba2b00}, {0x1006f39c6, 0x3}, {0xc000ca2790, 0x10})
        /Users/y.liu/go/go1.20/src/net/dial.go:422 +0x4c8
net/http.(*Transport).dial(0x100bffc40, {0x12a4a00d8, 0xc000ba2b00}, {0x1006f39c6, 0x3}, {0xc000ca2790, 0x10})
        /Users/y.liu/go/go1.20/src/net/http/transport.go:1176 +0x1bc
net/http.(*Transport).dialConn(0x100bffc40, {0x12a4a00d8, 0xc000ba2b00}, {{}, 0x0, {0x1006fa4c0, 0x4}, {0xc000ca2790, 0x10}, 0x0})
        /Users/y.liu/go/go1.20/src/net/http/transport.go:1614 +0x9d4
net/http.(*Transport).dialConnFor(0x0?, 0xc000b151e0)
        /Users/y.liu/go/go1.20/src/net/http/transport.go:1456 +0xc8
created by net/http.(*Transport).queueForDial
        /Users/y.liu/go/go1.20/src/net/http/transport.go:1425 +0x10c
```

**How to fix it: Not using the sync.Pool object pool anymore.**
```
// Handle registers a new route with a matcher for the URL path and method.
func (r *Router) Handle(method, relativePath string, h HandlerFunc, filters ...FilterFunc) {
	next := http.Handler(http.HandlerFunc(func(res http.ResponseWriter, req *http.Request) {
		ctx := &wrapper{
			router: r,
			req:    req,
			res:    res,
			w:      responseWriter{code: http.StatusOK, w: res},
		}
		if err := h(ctx); err != nil {
			r.srv.ene(res, req, err)
		}
	}))
	next = FilterChain(filters...)(next)
	next = FilterChain(r.filters...)(next)
	r.srv.router.Handle(path.Join(r.prefix, relativePath), next).Methods(method)
}
```

#### Environment:
- Kratos version (use `kratos -v`): v2.6.2
- Go version (use `go version`): 
- OS (e.g: `cat /etc/os-release`):
- Others:

**Comment by lyouthzzz** [comment]
more detail: https://github.com/golang/go/issues/63927

**Comment by freehere107** [comment]
@lyouthzzz I still have this problem after updating to v2.7.2.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x63f1b2]

goroutine 3315105 [running]:
net.(*Resolver).lookupIPAddr(0x3a68320, {0x2316a70?, 0xc007a505a0}, {0x1e6ff2f, 0x3}, {0xc003c8bc20, 0x26})
	/opt/hostedtoolcache/go/1.19.13/x64/src/net/lookup.go:346 +0x8b2
net.(*Resolver).internetAddrList(0x2316a70?, {0x2316a70?, 0xc007a505a0?}, {0x1e6ff2f, 0x3}, {0xc003c8bc20?, 0x2b?})
	/opt/hostedtoolcache/go/1.19.13/x64/src/net/ipsock.go:288 +0x67a
net.(*Resolver).resolveAddrList(0x3a9db40?, {0x2316a70, 0xc007a505a0}, {0x1e7119f, 0x4}, {0x1e6ff2f?, 0x433a90?}, {0xc003c8bc20, 0x2b}, {0x0, ...})
	/opt/hostedtoolcache/go/1.19.13/x64/src/net/dial.go:222 +0x41b
net.(*Dialer).DialContext(0xc0000a22a0, {0x2316a70, 0xc007a505a0}, {0x1e6ff2f, 0x3}, {0xc003c8bc20, 0x2b})
	/opt/hostedtoolcache/go/1.19.13/x64/src/net/dial.go:410 +0x448
net/http.(*Transport).dial(0x0?, {0x2316a70?, 0xc007a505a0?}, {0x1e6ff2f?, 0x0?}, {0xc003c8bc20?, 0x8?})
	/opt/hostedtoolcache/go/1.19.13/x64/src/net/http/transport.go:1170 +0xda
net/http.(*Transport).dialConn(0x3a4bf40, {0x2316a70, 0xc007a505a0}, {{}, 0x0, {0xc006a357a0, 0x4}, {0xc003c8bc20, 0x2b}, 0x0})
	/opt/hostedtoolcache/go/1.19.13/x64/src/net/http/transport.go:1608 +0x83f
net/http.(*Transport).dialConnFor(0xc0041347e0?, 0xc003f138c0)
	/opt/hostedtoolcache/go/1.19.13/x64/src/net/http/transport.go:1450 +0xb0
created by net/http.(*Transport).queueForDial
	/opt/hostedtoolcache/go/1.19.13/x64/src/net/http/transport.go:1419 +0x3f2
```
