### ISSUE TITLE
kratos run runs successfully but docker run fails

### ISSUE THREAD

**Issue by sanyuanya** [go-kratos/kratos#3192]
#### What happened:
使用 docker run 运行报错 
```cmd
➜  portal git:(develop) ✗ docker run -it -p 5000:5000 -p 5001:5001 -v /Users/sanyuanya/hjworkspace/go_dev/portal/configs/config.yaml:/data/conf  zcpt-portal:v0.0.1
2024/02/05 08:22:29 maxprocs: Leaving GOMAXPROCS=8: CPU quota undefined
DEBUG msg=config loaded: conf format: 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x590308]

goroutine 1 [running]:
portal/internal/data.NewDB(0x4000033b60?, {0x2710?, 0x40006b6300?})
        /src/internal/data/data.go:28 +0x18
main.wireApp(0x4000572140?, 0x81c760?, {0x9e5fc0?, 0x4000035fc0})
        /src/cmd/portal/wire_gen.go:27 +0x3c
main.main()
        /src/cmd/portal/main.go:77 +0x47c
```

#### What you expected to happen:

这是使用 kratos run 成功
```cmd
➜  portal git:(develop) ✗ kratos run
2024/02/05 16:31:24 maxprocs: Leaving GOMAXPROCS=8: CPU quota undefined
DEBUG msg=config loaded: config.yaml format: yaml
INFO ts=2024-02-05T16:31:24+08:00 caller=http/server.go:317 service.id=sanyuanyadeiMac.local service.name= service.version= trace.id= span.id= msg=[HTTP] server listening on: [::]:5001
INFO ts=2024-02-05T16:31:24+08:00 caller=grpc/server.go:212 service.id=sanyuanyadeiMac.local service.name= service.version= trace.id= span.id= msg=[gRPC] server listening on: [::]:5002
```

#### Anything else we need to know?:
配置文件 /configs/config.yaml
```yaml
server:
  http:
    addr: 0.0.0.0:5001
    timeout: 1s
  grpc:
    addr: 0.0.0.0:5002
    timeout: 1s
data:
  database:
    driver: postgres
    source: host=x.x.x.x port=5432 user=**** password=**** dbname=**** sslmode=disable
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
```
Dockerfile 
```Dockerfile
FROM golang:1.21 AS builder

COPY . /src
WORKDIR /src

RUN GOPROXY=https://goproxy.cn make build

FROM debian:stable-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
		ca-certificates  \
        netbase \
        && rm -rf /var/lib/apt/lists/ \
        && apt-get autoremove -y && apt-get autoclean -y

COPY --from=builder /src/bin /app

WORKDIR /app

EXPOSE 5001
EXPOSE 5002
VOLUME /data/conf

CMD ["./portal", "-conf", "/data/conf"]

```

在 main.go 打印 
```go 
c := config.New(
		config.WithSource(
			file.NewSource(flagconf),
		),
	)
	defer c.Close()

	if err := c.Load(); err != nil {
		panic(err)
	}

	var bc conf.Bootstrap
	if err := c.Scan(&bc); err != nil {
		panic(err)
	}

	app, cleanup, err := wireApp(bc.Server, bc.Data, logger)
```
c: &{opts:{sources:[0x40002d2c70] decoder:0x2f9210 resolver:0x2f94d0 merge:0x2fc650} reader:0x4000218040 cached:{mu:{state:0 sema:0} read:{_:[] _:{} v:<nil>} dirty:map[] misses:0} observers:{mu:{state:0 sema:0} read:{_:[] _:{} v:<nil>} dirty:map[] misses:0} watchers:[0x40002b03c0]}

bc: {state:{NoUnkeyedLiterals:{} DoNotCompare:[] DoNotCopy:[] atomicMessageInfo:0x40000cfb00} sizeCache:0 unknownFields:[] Server:<nil> Data:<nil>}

data: <nil>

#### Environment:
- Kratos version (use `kratos -v`): kratos version v2.7.1
- Go version (use `go version`): go version go1.21.6 darwin/arm64
- OS (e.g: `cat /etc/os-release`):  MacOS
- Others:

**Comment by sanyuanya** [comment]
docker 配置文件映射有问题
