### ISSUE TITLE
bug in Quick Start

### ISSUE THREAD

**Issue by Brandon-lz** [go-kratos/kratos#3355]
#### What happened:
when I run the tutorial in https://go-kratos.dev/en/docs/getting-started/start, it comes out an error:
$ go generate ./...
```shell
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x58b24f]

goroutine 60 [running]:
go/types.(*Checker).handleBailout(0xc0001f6600, 0xc000333bd0)
        /home/gitpod/go/src/go/types/check.go:367 +0x88
panic({0x69a640?, 0x8be710?})
        /home/gitpod/go/src/runtime/panic.go:770 +0x132
go/types.(*StdSizes).Sizeof(0x0, {0x747128, 0x8c2c40})
        /home/gitpod/go/src/go/types/sizes.go:228 +0x30f
go/types.(*Config).sizeof(...)
        /home/gitpod/go/src/go/types/sizes.go:333
go/types.representableConst.func1({0x747128?, 0x8c2c40?})
        /home/gitpod/go/src/go/types/const.go:76 +0x9e
go/types.representableConst({0x748d60, 0x8b7000}, 0xc0001f6600, 0x8c2c40, 0xc000331fe8)
        /home/gitpod/go/src/go/types/const.go:92 +0x192
go/types.(*Checker).representation(0xc0001f6600, 0xc00009d040, 0x8c2c40)
        /home/gitpod/go/src/go/types/const.go:256 +0x65
go/types.(*Checker).implicitTypeAndValue(0xc0001f6600, 0xc00009d040, {0x747128, 0x8c2c40})
        /home/gitpod/go/src/go/types/expr.go:375 +0x2d7
go/types.(*Checker).convertUntyped(0xc0001f6600, 0xc00009d040, {0x747128, 0x8c2c40})
        /home/gitpod/go/src/go/types/const.go:289 +0x3f
go/types.(*Checker).matchTypes(0xc0001f6600, 0xc00009d000, 0xc00009d040)
        /home/gitpod/go/src/go/types/expr.go:926 +0x79
go/types.(*Checker).binary(0xc0001f6600, 0xc00009d000, {0x747e18, 0xc00031c0f0}, {0x747ea8, 0xc00007e1e0}, {0x7483e8, 0xc00007e200}, 0x28, 0x133)
        /home/gitpod/go/src/go/types/expr.go:800 +0x166
go/types.(*Checker).exprInternal(0xc0001f6600, 0x0, 0xc00009d000, {0x747e18, 0xc00031c0f0}, {0x0, 0x0})
        /home/gitpod/go/src/go/types/expr.go:1416 +0x206
go/types.(*Checker).rawExpr(0xc0001f6600, 0x0, 0xc00009d000, {0x747e18?, 0xc00031c0f0?}, {0x0?, 0x0?}, 0x0)
        /home/gitpod/go/src/go/types/expr.go:979 +0x19e
go/types.(*Checker).expr(0xc0001f6600, 0x7474c0?, 0xc00009d000, {0x747e18?, 0xc00031c0f0?})
        /home/gitpod/go/src/go/types/expr.go:1513 +0x30
go/types.(*Checker).stmt(0xc0001f6600, 0x0, {0x748208, 0xc00009c2c0})
        /home/gitpod/go/src/go/types/stmt.go:570 +0x11f2
go/types.(*Checker).stmtList(0xc0001f6600, 0x0, {0xc00007e360?, 0x0?, 0x0?})
        /home/gitpod/go/src/go/types/stmt.go:121 +0x85
go/types.(*Checker).funcBody(0xc0001f6600, 0x747128?, {0xc00030c068?, 0x8c2e20?}, 0xc00009cd40, 0xc00031c180, {0x0?, 0x0?})
        /home/gitpod/go/src/go/types/stmt.go:41 +0x331
go/types.(*Checker).funcDecl.func1()
        /home/gitpod/go/src/go/types/decl.go:852 +0x3a
go/types.(*Checker).processDelayed(0xc0001f6600, 0x0)
        /home/gitpod/go/src/go/types/check.go:467 +0x162
go/types.(*Checker).checkFiles(0xc0001f6600, {0xc000316008, 0x1, 0x1})
        /home/gitpod/go/src/go/types/check.go:411 +0x1cc
go/types.(*Checker).Files(...)
        /home/gitpod/go/src/go/types/check.go:372
golang.org/x/tools/go/packages.(*loader).loadPackage(0xc000182000, 0xc00009eab0)
        /workspace/go/pkg/mod/golang.org/x/tools@v0.6.0/go/packages/packages.go:1052 +0xa72
golang.org/x/tools/go/packages.(*loader).loadRecursive.func1()
        /workspace/go/pkg/mod/golang.org/x/tools@v0.6.0/go/packages/packages.go:851 +0x1a9
sync.(*Once).doSlow(0x0?, 0x0?)
        /home/gitpod/go/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
        /home/gitpod/go/src/sync/once.go:65
golang.org/x/tools/go/packages.(*loader).loadRecursive(0x0?, 0x0?)
        /workspace/go/pkg/mod/golang.org/x/tools@v0.6.0/go/packages/packages.go:839 +0x4a
golang.org/x/tools/go/packages.(*loader).loadRecursive.func1.1(0x0?)
        /workspace/go/pkg/mod/golang.org/x/tools@v0.6.0/go/packages/packages.go:846 +0x26
created by golang.org/x/tools/go/packages.(*loader).loadRecursive.func1 in goroutine 59
        /workspace/go/pkg/mod/golang.org/x/tools@v0.6.0/go/packages/packages.go:845 +0x94
exit status 2
cmd/helloworld/wire_gen.go:3: running "go": exit status 1
```

#### How to reproduce it (as minimally and precisely as possible):
just run follow official tutorial
#### Environment:
- Kratos version (use `kratos -v`):
- Go version (use `go version`):1.22.2
- OS (e.g: `cat /etc/os-release`):linux/amd64
- Others:

**Comment by realityone** [comment]
Upgrade `golang.org/x/tool` to latest.

- https://github.com/ent/ent/issues/3864
